import recipe1 from '../../assets/recipes/1.png'
import recipe2 from '../../assets/recipes/2.png'
import recipe3 from '../../assets/recipes/3.png'
import recipe4 from '../../assets/recipes/4.png'
import recipe5 from '../../assets/recipes/5.webp'
import recipe6 from '../../assets/recipes/6.webp'
import recipe7 from '../../assets/recipes/7.webp'
import recipe8 from '../../assets/recipes/8.webp'
import recipe9 from '../../assets/recipes/9.webp'
import recipe10 from '../../assets/recipes/10.webp'
import recipe11 from '../../assets/recipes/11.png'
import recipe12 from '../../assets/recipes/12.png'
import recipe13 from '../../assets/recipes/13.png'
import recipe14 from '../../assets/recipes/14.png'
import recipe15 from '../../assets/recipes/15.png'
import recipe16 from '../../assets/recipes/16.png'
const RecipesData = [
  {
    number: 1,
    image: recipe1,
    title: 'Enjoy haldi barfi',
    subtitle: 'In your Rabri',
    ingredients: [
      '•Rabri (250 ml):',
      '•1 liter full-fat milk',
      '•2-3 tbsp sugar (adjust to taste)',
      '•1/2 tsp cardamom powder',
      '•A few saffron strands (optional)',
      '•Chopped nuts (almonds, pistachios) for garnish',
      '',
      '•Ice Cream (Vanilla or Kesar Pista flavor, 250 gms)',
      '•Haldi Barfi (200 gms)',
    ],
    instructions: [
      '•For the Rabri:',
      'a. Boil the milk in a wide pan on medium heat. Once it boils, reduce to low heat and continue cooking, scraping the sides of the pan to collect the cream.',
      'b. Stir occasionally to prevent burning. Let it simmer until it reduces to about 1/3 of its original quantity.',
      'c. Add sugar, cardamom powder, and saffron, and let it cook for another 5-7 minutes. The milk should become thick and creamy.',
      'd. Turn off the heat and let it cool down. Chill it in the fridge before serving.',

      '•Assembling the Fusion Dessert:',
      'a. In a serving glass or bowl, add crumbled pieces of Haldi Barfi as the base layer.',
      'b. Add a generous scoop of chilled Rabri over the barfi.',
      'c. Place a scoop of Vanilla or Kesar Pista Ice Cream on top of the rabri.',
      'd. Garnish with more chopped nuts and saffron strands for an extra touch of richness.',

      '•Serving Suggestion:',
      'a. Serve immediately to enjoy the combination of the warm Haldi Barfi, the chilled Rabri, and the cold, creamy Ice Cream.',
      '•This dessert brings out the distinct flavors of turmeric-infused barfi, creamy rabri, and cool ice cream into one delightful dish!',
    ],
    colors: {
      bg: '#B7D6FE',
      title: '#FFFFFF',
      subtitle: '#4D76AB',
      ingredientsTitle: '#628ABE',
      ingredients: '#000000',
      instructionsTitle: '#628ABE',
      instructions: '#000000',
    },
  },
  {
    number: 2,
    image: recipe5,
    title: 'Enjoy haldi barfi',
    subtitle: 'In your shakes and smoothies',
    ingredients: [
      '1 liter full-fat milk',
      '1/4 cup basmati rice (washed and soaked for 30 minutes)',
      '100g Sanjeevani haldi barfi (grated or crumbled)',
      '5-6 green cardamom pods (crushed)',
      '8-10 almonds (sliced)',
      '10 cashews (halved)',
      '8-10 pistachios (sliced)',
      'A pinch of saffron (optional, soaked in 1 tbsp warm milk)',
      '1 tbsp ghee',
    ],
    instructions: [
      'Heat the ghee in a heavy-bottomed pan, add the soaked rice, and lightly sauté for 2-3 minutes on low heat until fragrant.',
      'Add milk to the pan and bring it to a boil. Reduce the heat and simmer, stirring occasionally to prevent sticking, until the rice is cooked and the milk has thickened (about 25-30 minutes).',
      'Add the crumbled Sanjeevani haldi barfi and stir well until it dissolves completely into the kheer, giving it a golden hue and a sweet-tangy flavor.',
      'Add the crushed cardamom pods and saffron (if using), and cook for another 5 minutes to blend the flavors.',
      'Turn off the heat, and garnish with sliced almonds, cashews, and pistachios.',
      'Serve warm or chilled as per your preference.',
    ],
    colors: {
      bg: '#FFD57A',
      title: '#FFFFFF',
      subtitle: '#D6B100',
      ingredientsTitle: '#EBC50F',
      ingredients: '#000000',
      instructionsTitle: '#EBC50F',
      instructions: '#000000',
    },
  },
  {
    number: 3,
    image: recipe8,
    title: 'Enjoy haldi barfi',
    subtitle: 'In your Warm Drinks!',
    ingredients: [
      '1 cup water',
      '1 cup milk (or any non-dairy milk alternative)',
      '1 small piece of haldi barfi (adjust sweetness according to preference)',
      '1-2 tsp tea leaves (black or green, depending on preference)',
      '1-inch piece of ginger (optional)',
      '1-2 cardamom pods (optional)',
      'A pinch of black pepper (optional, for enhancing turmeric absorption)',
    ],
    instructions: [
      'Boil Water: In a pot, bring 1 cup of water to a boil. If you&apos;ng ginger or cardamom, add it at this stage to let the flavors infuse',
      'Add Tea Leaves: Once the water is boiling, add your preferred tea leaves and let it steep for a couple of minutes.',
      'Add Milk: Pour in 1 cup of milk and allow the mixture to simmer on low heat.',
      'Add Haldi Barfi: Add the small piece of haldi barfi to the simmering tea. Stir well to let the barfi melt into the tea and blend the flavors.',
      'Strain and Serve: After simmering for a few minutes, strain the tea into a cup. Optionally, you can add a pinch of black pepper for an extra kick and to enhance the benefits of turmeric.',
      'Enjoy your haldi barfi tea, which combines the warmth of traditional chai with the sweetness and earthiness of haldi barfi!',
    ],
    colors: {
      bg: '#FDE5B6',
      title: '#FFFFFF',
      subtitle: '#B08A40',
      ingredientsTitle: '#D0AA5E',
      ingredients: '#000000',
      instructionsTitle: '#D0AA5E',
      instructions: '#000000',
    },
  },
  {
    number: 4,
    image: recipe9,
    title: 'Enjoy haldi barfi',
    subtitle: 'In your Meetha Paratha!',
    ingredients: [
      '1 cup wheat flour (atta)',
      'Water (as needed for kneading)',
      'Ghee or oil (for frying)',
      '2-3 pieces of haldi barfi (grated or crumbled)',
      '1-2 tbsp sugar (optional, for extra sweetness)',
      'A pinch of cardamom powder (optional, for flavor)',
      'A pinch of salt',
    ],
    instructions: [
      '1.Prepare the Dough:',
      '• In a mixing bowl, add the wheat flour and a pinch of salt.',
      '• Gradually add water and knead into a soft dough.',
      '• Cover the dough and let it rest for about 10-15 minutes.',

      '2. Prepare the Haldi Barfi Filling:',
      '• Grate or crumble the haldi barfi into small pieces.',
      '• If you prefer extra sweetness, mix in 1-2 tbsp of sugar.',
      '• You can also add a pinch of cardamom powder to enhance the flavor',

      '3. Stuff the Paratha:',
      '• Divide the dough into small balls (about lemon-sized).',
      '• Roll out each dough ball into a small circle.',
      '• Place the crumbled haldi barfi mixture in the center.',
      '• Carefully fold the edges over the filling, sealing it well.',
      '• Gently roll it out again into a flat, round paratha (ensure the filling doesn’t spill out).',

      '4. Fry the Paratha:',
      '• Heat a tawa or frying pan on medium heat.',
      '• Place the rolled paratha on the hot pan and cook for about 1-2 minutes on each side.',
      '• Add a small amount of ghee or oil and fry the paratha until it turns golden brown and crispy on both sides.',

      '5. Serve:',
      '• Once cooked, remove from the pan and serve hot with a drizzle of honey, yogurt, or any side of your choice.',

      '• This haldi barfi meetha paratha has a rich and unique flavor, combining the earthy sweetness of haldi barfi with the crispy, buttery layers of the paratha.',
    ],
    colors: {
      bg: '#EFDACE',
      title: '#FFFFFF',
      subtitle: '#96756A',
      ingredientsTitle: '#B38C7F',
      ingredients: '#000000',
      instructionsTitle: '#B38C7F',
      instructions: '#000000',
    },
  },
  {
    number: 5,
    image: recipe6,
    title: 'Enjoy haldi barfi',
    subtitle: 'In your Ice Cream!',
    ingredients: [
      '• Rabri (250 ml):',
      '• 1 liter full-fat milk',
      '• 2-3 tbsp sugar (adjust to taste)',
      '• 1/2 tsp cardamom powder',
      '• A few saffron strands (optional)',
      '• Chopped nuts (almonds, pistachios) for garnish',

      '• Ice Cream (Vanilla or Kesar Pista flavor, 250 gms)',
      '• Haldi Barfi (200 gms)',
    ],
    instructions: [
      '• For the Rabri:',
      'a. Boil the milk in a wide pan on medium heat. Once it boils, reduce to low heat and continue cooking, scraping the sides of the pan to collect the cream.',
      'b. Stir occasionally to prevent burning. Let it simmer until it reduces to about 1/3 of its original quantity.',
      'c. Add sugar, cardamom powder, and saffron, and let it cook for another 5-7 minutes. The milk should become thick and creamy.',
      'd. Turn off the heat and let it cool down. Chill it in the fridge before serving',

      '• Assembling the Fusion Dessert:',
      'a. In a serving glass or bowl, add crumbled pieces of Haldi Barfi as the base layer.',
      'b. Add a generous scoop of chilled Rabri over the barfi.',
      'c. Place a scoop of Vanilla or Kesar Pista Ice Cream on top of the rabri.',
      'd. Garnish with more chopped nuts and saffron strands for an extra touch of richness.',

      '• Serving Suggestion:',
      '• Serve immediately to enjoy the combination of the warm Haldi Barfi, the chilled Rabri, and the cold, creamy Ice Cream.',
      '• This dessert brings out the distinct flavors of turmeric-infused barfi, creamy rabri, and cool ice cream into one delightful dish!',
    ],
    colors: {
      bg: '#E9DFD0',
      title: '#FFFFFF',
      subtitle: '#A49885',
      ingredientsTitle: '#BBAD97',
      ingredients: '#000000',
      instructionsTitle: '#BBAD97',
      instructions: '#000000',
    },
  },
  {
    number: 6,
    image: recipe7,
    title: 'Enjoy haldi barfi',
    subtitle: 'In your Energy Bites!',
    ingredients: [
      '2-3 pieces of haldi barfi (crumbled)',
      '1 cup rolled oats',
      '½ cup almond flour (or ground almonds)',
      '½ cup mixed seeds (chia seeds, flax seeds, or sunflower seeds)',
      '¼ cup chopped nuts (almonds, cashews, or walnuts)',
      '¼ cup dried fruits (raisins, dates, or dried cranberries)',
      '2 tbsp nut butter (like almond or peanut butter)',
      '2 tbsp honey or maple syrup (optional, for extra sweetness)',
      '1 tsp cinnamon powder',
      'A pinch of cardamom powder (optional)',
      'A pinch of salt',
    ],
    instructions: [
      '1. Toast the Oats and Nuts (Optional):',
      '• In a dry pan, lightly toast the oats and chopped nuts over medium heat for 3-5 minutes until they are slightly golden and fragrant. Set aside to cool.',
      '2. Prepare the Mixture:',
      '• In a large mixing bowl, combine the crumbled haldi barfi, toasted oats, almond flour, mixed seeds, chopped nuts, and dried fruits.',
      '• Add cinnamon powder, cardamom powder (if using), and a pinch of salt for enhanced flavor.',
      '3. Add the Wet Ingredients:',
      '• Stir in the nut butter and honey or maple syrup (if using). Mix everything well until the ingredients start to come together and form a sticky dough.',
      '4. Form the Energy Bites:',
      '• Take small portions of the mixture (about a tablespoon each) and roll them into bite-sized balls using your hands. If the mixture feels too dry, you can add a little more nut butter or honey to help bind it.',
      '5. Chill and Store:',
      '• Place the energy bites on a plate and refrigerate for 20-30 minutes to firm up.',
      '•Once set, store the energy bites in an airtight container in the fridge for up to a week.',
      '6. Variations:',
      '• Coconut Coating: Roll the energy bites in shredded coconut for extra texture and flavor.',
      '• Chocolate Drizzle: Drizzle melted dark chocolate over the energy bites for a decadent touch.',
      '• These Haldi Barfi Energy Bites are packed with nutrients from the oats, nuts, seeds, and dried fruits, while the haldi barfi adds a sweet, earthy flavor and the health benefits of turmeric. Perfect for a pre- or post-workout snack or a quick energy boost during the day!',
    ],
    colors: {
      bg: '#EED2AB',
      title: '#FFFFFF',
      subtitle: '#A49885',
      ingredientsTitle: '#BBAD97',
      ingredients: '#000000',
      instructionsTitle: '#BBAD97',
      instructions: '#000000',
    },
  },
  {
    number: 7,
    image: recipe10,
    title: 'Enjoy haldi barfi',
    subtitle: 'In your Baked Foods!',
    ingredients: [
      'For the Cookie Dough:',
      '• 1 ½ cups all-purpose flour',
      '• ½ cup unsalted butter (softened),',
      '• ½ cup powdered sugar',
      '• 1 tsp vanilla extract',
      '• ¼ tsp baking powder',
      '• A pinch of salt',

      'For the Filling:',
      '• 2-3 pieces of haldi barfi (grated or crumbled)',
      '•A pinch of cardamom powder (optional, for enhanced flavor)',
      '• A handful of chopped nuts (optional, for texture)',
    ],
    instructions: [
      '1. Prepare the Cookie Dough:',
      '• In a large bowl, cream together the softened butter and powdered sugar until light and fluffy.',
      '• Add vanilla extract and mix well.',
      '• In a separate bowl, whisk together the flour, baking powder, and salt.',
      '• Gradually add the dry ingredients to the wet mixture, mixing until it forms a soft dough. If the dough feels too dry, you can add a teaspoon of milk.',
      '• Wrap the dough in plastic wrap and refrigerate for 20-30 minutes to firm up.',

      '2. Prepare the Haldi Barfi Filling:',
      '• Grate or crumble the haldi barfi into small pieces.',
      '• If desired, mix in a pinch of carda',
      '• mom powder for an aromatic touch, and some chopped nuts for added texture',

      '3. Assemble the Cookies:',
      '• Preheat the oven to 350°F (175°C) and line a baking sheet with parchment paper.',
      '• Take the chilled dough and divide it into small, equal-sized balls (about a tablespoon of dough per ball).',
      '• Flatten each ball into a small circle with your hands.',
      '• Place a small amount of the haldi barfi filling in the center of the dough circle.',
      '• Gently fold the dough over the filling, sealing it completely, and shape it back into a ball.',
      '• Place the filled cookie dough balls on the baking sheet, spacing them slightly apart.',

      '4. Bake the Cookies:',
      '• Bake in the preheated oven for 12-15 minutes or until the edges are slightly golden.',
      '• Remove from the oven and allow the cookies to cool on a wire rack.',

      '5. Serve:',
      '• Once cooled, enjoy your haldi barfi stuffed cookies with a cup of tea or coffee. The sweet, spiced filling inside a buttery, crumbly cookie is a delightful fusion of traditional Indian and Western flavors.',
      'This unique recipe combines the sweetness of haldi barfi with the crispness of baked cookies, making it a perfect fusion dessert for any occasion!',
    ],
    colors: {
      bg: '#FFE3BC',
      title: '#FFFFFF',
      subtitle: '#D99451',
      ingredientsTitle: '#E7B179',
      ingredients: '#000000',
      instructionsTitle: '#E7B179',
      instructions: '#000000',
    },
  },
  {
    number: 8,
    image: recipe4,
    title: 'Enjoy haldi barfi',
    subtitle: 'In your Kheer!',
    ingredients: [
      '1 liter full-fat milk ',
      '1/4 cup basmati rice (washed and soaked for 30 minutes)',
      ' 100g Sanjeevani haldi barfi (grated or crumbled)',
      '5-6 green cardamom pods (crushed)',
      '8-10 almonds (sliced)',
      '8-10 cashews (halved)',
      '8-10 pistachios (sliced)',
      'A pinch of saffron (optional, soaked in 1 tbsp warm milk)',
      '1 tbsp ghee',
    ],
    instructions: [
      'Heat the ghee in a heavy-bottomed pan, add the soaked rice, and lightly saute for 2-3 minutes on low heat until fragrant.',
      'Add milk to the pan and bring it to a boil. Reduce the heat and simmer, stirring occasionally to prevent sticking, until the rice is cooked and the milk has thickened (about 25-30 minutes)',
      'Add the crumbled Sanjeevani haldi barfi and stir well until it dissolves completely into the kheer, giving it a golden hue and a sweet-tangy flavor.',
      'Add the crushed cardamom pods and saffron (if using), and cook for another 5 minutes to blend the flavors.',
      'Turn off the heat, and garnish with sliced almonds, cashews, and pistachios',
      'Serve warm or chilled as per your preference.',
    ],
    colors: {
      bg: '#FFD789',
      title: '#FFFFFF',
      subtitle: '#AA863F',
      ingredientsTitle: '#AA863F',
      ingredients: '#000000',
      instructionsTitle: '#AA863F',
      instructions: '#000000',
    },
  },

  // final
  {
    number: 9,
    image: recipe2,
    title: 'Enjoy haldi barfi',
    subtitle: 'In your Spring Rolls!',
    ingredients: [
      '1 pics spring roll sheet  ',
      '1 pic ladd',
      '100gmWhipcream ',
      '10gm pistachio ',
      '10gm almond ',
      '2 tea spoon sugar ',
      ' 10gm fresh Rose patle',
    ],
    instructions: [
      'Prepare the Filling:',

      'Crumble the laddu into small pieces in a bowl.',
      'Chop the pistachios and almonds into small pieces.',
      'In a separate bowl, whip the cream until it becomes fluffy.',
      'Mix the crumbled laddu, chopped pistachios, chopped almonds, and sugar into the whipped cream. Add rose petals into the mixture for a floral touch and stir gently.',
      'Prepare the Spring Roll Sheet:',

      'Lay the spring roll sheet flat on a clean surface.',
      'If necessary, lightly heat it so it’s flexible (you can do this by quickly warming it in a pan for a few seconds).',
      'Assemble the Spring Rolls:',

      'Place a small portion of the cream mixture onto the center of the spring roll sheet.',
      'Fold the sides of the sheet over the filling, then roll it tightly from the bottom, like a traditional spring roll.',
      'Cooking (Optional):',

      'Heat a little oil in a pan over medium heat.',
      'Fry the spring roll for about 2-3 minutes on each side, or until golden brown and crispy. Alternatively, you can bake them in an oven at 180°C (350°F) for about 10-12 minutes until crispy.',
      'Serve:',

      'Once cooked, remove from heat and allow them to cool slightly.',
      'Garnish with a few more chopped pistachios and rose petals before serving.',
      'This will give you a sweet, crispy dessert spring roll. Enjoy!',
    ],
    colors: {
      bg: '#E4D1C6',
      title: '#FFFFFF',
      subtitle: '#9D8E86',
      ingredientsTitle: '#B2A39B',
      ingredients: '#000000',
      instructionsTitle: '#B2A39B',
      instructions: '#000000',
    },
  },
  {
    number: 10,
    image: recipe3,
    title: 'Enjoy haldi barfi',
    subtitle: 'In your Crepe Suzette!',
    ingredients: [
      '1 cup rice flour',
      '1/2 cup semolina',
      '1/2 cup wheat flour',
      '2 cups warm water',
      '1 cup milk',
      '1 piece laddu (crushed)',
      '30g butter',
      '20g semolina (for cooking)',
      '30g fresh rose petals',
    ],
    instructions: [
      'Make the Crepe Batter:',
      'In a large mixing bowl, combine the rice flour, semolina, and wheat flour.',
      'Gradually add the warm water and milk while whisking continuously to prevent lumps.',
      'Mix until you have a smooth batter. The consistency should be similar to pancake batter—thin enough to spread easily in the pan but not too runny.',

      'Prepare the Laddu Filling: ',
      'Crumble the laddu into small pieces or mash it. This will add a sweet flavor to the crepes.;',
      'Set aside.',

      'Cook the Crepes:',
      'Heat a non-stick skillet or crepe pan over medium heat and melt a little butter.',
      'Pour a ladleful of the crepe batter into the pan, tilting the pan to spread it evenly.',
      'Cook for about 1-2 minutes on one side until golden brown, then flip and cook the other side for about 1 minute. Repeat with the remaining batter. Set the cooked crepes aside.',

      'Prepare the Rose Butter Sauce:',
      'In the same pan, melt the 30g butter over low heat.',
      'Add the crumbled laddu to the melted butter and let it melt together, stirring constantly to create a smooth mixture.',
      'Add a handful of fresh rose petals to the pan and cook briefly to infuse the butter with a delicate rose fragrance.',

      'Assemble the Crepes Suzette:',
      'Place each cooked crepe into the pan with the laddu-rose butter sauce. Fold the crepes into quarters (fold in half and then in half again).',
      'Let the crepes soak briefly in the sauce, allowing the flavors to meld.',

      'Serve:',
      'Plate the folded crepes and drizzle them with any remaining rose butter sauce from the pan. Garnish with extra fresh rose petals for a fragrant and elegant touch.',
    ],
    colors: {
      bg: '#EBE5E0',
      title: '#FFFFFF',
      subtitle: '#9D8E86',
      ingredientsTitle: '#B2A39B',
      ingredients: '#000000',
      instructionsTitle: '#B2A39B',
      instructions: '#000000',
    },
  },

  {
    number: 11,
    image: recipe11,
    title: 'Enjoy haldi barfi',
    subtitle: 'In your Phirni!',
    ingredients: [
      '100 grams Samak rice(or barnyard millet)',
      '250 ml Milk',
      '3 pieces Haldi barfi(turmeric fudge)',
      '10 grams Fox nuts(makhana)',
      '20 grams Pistachios',
      '30 grams Almonds',
      '10 grams Fresh rose petals',
    ],
    instructions: [
      'Prepare the Rice:',
      'Wash the Samak rice thoroughly. Soak it in water for about 30 minutes, then drain.',

      'Prepare the Nuts and Rose Petals:',
      'Roast the Fox nuts in a dry pan for a few minutes until they become crunchy.Slice the Pistachios and Almonds thinly.Gently wash the fresh rose petals to remove any dirt.',

      'Make the Phirni:',
      'In a pan, add the milk and bring it to a boil.',
      'Add the soaked Samak rice and cook it in the milk on low flame until the rice softens and the milk thickens (about 15-20 minutes).',

      'Add Haldi Barfi:',
      'Cut the Haldi barfi into small pieces and add them to the pan. Stir to incorporate. The barfi will melt and flavor the mixture.',

      'Add the Nuts and Rose Petals:',
      'Once the phirni thickens to your desired consistency, add the roasted Fox nuts, sliced Pistachios, and Almonds. Stir well.Garnish the dessert with fresh rose petals for a fragrant touch.',

      'Serve:',
      'Serve warm or chilled, depending on your preference.',
    ],
    colors: {
      bg: '#F7EBB7',
      title: '#FFFFFF',
      subtitle: '#B2A772',
      ingredientsTitle: '#CDC187',
      ingredients: '#000000',
      instructionsTitle: '#B2A39B',
      instructions: '#000000',
    },
  },

  {
    number: 12,
    image: recipe12,
    title: 'Enjoy haldi barfi',
    subtitle: 'In your Bread crumbs!',
    ingredients: [
      '50 gram bread crumbs',
      '1 piece of turmeric cardamom barfi',
      '50 gram maida (all-purpose flour)',
      '30 gram chocolate syrup',
      '100g whipped cream',
      '10 gram fresh rose petals',
    ],
    instructions: [
      'Prepare the Filling: ',
      'A) Crumble the piece of turmeric cardamom barfi into small pieces.',
      'In a mixing bowl, add the crumbled barfi, bread crumbs, and maida (flour). Mix well to combine the dry ingredients.',

      'B)Prepare the Chocolate Cream:',
      'In another bowl, whip the cream until soft peaks form.',
      'C) Gently fold in the chocolate syrup into the whipped cream, blending it well. This will give you a chocolate-flavored cream mixture.',

      'Combine the Mixture: ',
      'A) Gradually add the chocolate cream into the dry ingredient mixture (bread crumbs, barfi, and maida). Mix everything together until you form a dough-like consistency.',

      'Shape and Set: ',
      'A) Roll the mixture into small balls or shape them into squares, depending on your preference. If the dough is too sticky, you can dust your hands with a little maida.',
      'B) Place the shaped pieces on a tray lined with parchment paper.',

      'Chill the Mixture : ',
      'A) Refrigerate for about 1-2 hours to set and firm up the mixture.',

      'Garnish with Rose Petals: ',
      'A) Once the pieces are chilled and set, garnish each piece with a small fresh rose petal to add a fragrant touch and a bit of elegance.',

      'Serve: ',
      'A)Serve these sweet bites chilled as a dessert or snack.',
      'B)Enjoy your creative, aromatic, and flavorful dessert!',
    ],
    colors: {
      bg: '#FFE2A6',
      title: '#FFFFFF',
      subtitle: '#B49E72',
      ingredientsTitle: '#C9B283',
      ingredients: '#000000',
      instructionsTitle: '#C9B283',
      instructions: '#000000',
    },
  },

  {
    number: 13,
    image: recipe13,
    title: 'Enjoy Haldi Barfi',
    subtitle: 'In your Panjeere!',
    ingredients: [
      '250 grams Whole wheat flour',
      '100 grams Ghee (clarified butter)',
      '1-2 pieces Haldi Barfi from Mother’s Kitchen',
      '50 grams Fox nuts (makhana)',
      '30 grams Almonds (sliced)',
      '30 grams Cashews (chopped)',
      '30 grams Pistachios (sliced)',
      '50 grams Dried coconut (grated)',
      '20 grams Gond (edible gum)',
      '1 teaspoon Cardamom powder',
      '20 grams Raisins',
    ],
    instructions: [
      '1. Roast the Fox Nuts and Nuts:',
      '   Dry roast the Fox nuts in a pan until they become crunchy. Set aside.',
      '   Lightly roast the Almonds, Cashews, and Pistachios in the same pan without oil. Set aside.',
      '',
      '2. Fry the Edible Gum (Gond):',
      '   Heat 1-2 teaspoons of Ghee in a pan and fry the Gond on medium heat until it puffs up. Crush it into small pieces once it cools down.',
      '',
      '3. Roast the Wheat Flour:',
      '   In a large, heavy-bottomed pan, heat the remaining Ghee. Add the whole wheat flour and roast on low heat until it turns golden brown and gives a nutty aroma. Stir constantly to avoid burning.',
      '',
      '4. Add the Coconut:',
      '   Add the grated dried coconut to the roasted wheat flour and stir well for 2-3 minutes.',
      '',
      '5. Mix in the Barfi and Spices:',
      '   Turn off the heat and let the mixture cool slightly. Add the powdered Barfi, cardamom powder, and mix thoroughly.',
      '',
      '6. Combine the Ingredients:',
      '   Add the roasted Fox nuts, nuts, crushed Gond, and raisins to the mixture. Stir well to combine all the ingredients evenly.',
      '',
      '7. Serve and Store:',
      '   Once the Panjiri cools completely, transfer it to an airtight container. It can be enjoyed as a healthy snack or a nutritious dessert.',
      '',
      'This Panjiri recipe is wholesome and rich, perfect for festive occasions or as a nourishing treat.',
    ],
    colors: {
      bg: '#FFD0A6',
      title: '#FFFFFF',
      subtitle: '#BA8D67',
      ingredientsTitle: '#BA8D67',
      ingredients: '#000000',
      instructionsTitle: '#BA8D67',
      instructions: '#000000',
    },
  },
  {
    number: 14,
    image: recipe14,
    title: 'Enjoy Dark Roast Bar',
    subtitle: 'In your Donut!',
    ingredients: [
      '2 slices of bread (edges trimmed)',
      '40 grams Mother&apos;s Kitchen Dark Roast Bar (melted or in small pieces)',
      'Coating & Batter:',
      '½ cup all-purpose flour (maida)',
      '2 tablespoons corn flour',
      '½ teaspoon baking powder',
      '½ cup milk',
      '1 teaspoon vanilla essence (optional)',
      'A pinch of salt',
      'For Frying:',
      'Oil or butter (for deep frying)',
      'For Chocolate Coating:',
      '½ cup melted Mother&apos;s Kitchen Dark Roast Bar',
      '1 teaspoon butter (for a glossy chocolate glaze)',
      '1 tablespoon colorful sprinkles (optional, for topping)',
    ],
    instructions: [
      '1. Prepare the Bread Base:',
      '   Take two slices of bread and trim the edges.',
      '   Place a small amount of Mother&apos;s Kitchen Dark Roast Bar (melted or in pieces) between the slices.',
      '   Gently press the edges together to seal.',
      '',
      '2. Make the Batter:',
      '   In a bowl, mix all-purpose flour, corn flour, baking powder, and salt.',
      '   Gradually add milk and vanilla essence, stirring continuously until you get a smooth batter.',
      '',
      '3. Coat & Fry:',
      '   Heat oil or butter in a deep pan for frying.',
      '   Dip the prepared bread in the batter, ensuring an even coat.',
      '   Deep fry until golden brown and crispy. Remove and drain excess oil on a paper towel.',
      '',
      '4. Chocolate Coating:',
      '   Melt Mother&apos;s Kitchen Dark Roast Bar with 1 teaspoon of butter.',
      '   Dip or drizzle the fried snack with melted chocolate.',
      '   Sprinkle with colorful sprinkles for extra flavor.',
      '',
      '5. Serve & Enjoy:',
      '   Let the chocolate coating set slightly before serving.',
      '   For a richer taste, add crushed nuts, caramel drizzle, or white chocolate drizzle.',
      '',
      'Enjoy your homemade chocolate-coated donut-style snack! 🍩✨',
    ],
    colors: {
      bg: '#EFE2AC',
      title: '#FFFFFF',
      subtitle: '#716842',
      ingredientsTitle: '#716842',
      ingredients: '#000000',
      instructionsTitle: '#716842',
      instructions: '#000000',
    },
  },
  {
    number: 15,
    image: recipe15,
    title: 'Enjoy Dark Roast Bar',
    subtitle: 'In your Chocolate Roll !',
    ingredients: [
      'Dark chocolate – 30g',
      'Bread – 2 pieces',
      'Milk – 2 tbsp',
      'Butter – 1 tsp',
      'Chocolate syrup – for garnishing',
    ],
    instructions: [
      '1. ⁠Melt the Chocolate:',
      '   Break the dark chocolate into small pieces.',
      '   Heat the milk in a pan and add the chocolate.',
      '   Stir continuously on low heat until the chocolate melts completely.',
      '',
      '2. ⁠Prepare the Bread:',
      '   Trim the edges of the bread slices.',
      '   Flatten the bread using a rolling pin.',
      '',
      '3. ⁠Make the Roll:',
      '   Spread the melted chocolate evenly over the bread.',
      '   Roll the bread carefully and seal the edges using a little water',
      '   ',
      '',
      '4. ⁠Garnish and Serve:',
      '   Place the roll on a plate and drizzle chocolate syrup over it..',
      '',
      'Serve  chilled.',
    ],
    colors: {
      bg: '#FFD7F3',
      title: '#FFFFFF',
      subtitle: '#9C5988',
      ingredientsTitle: '#9C5988',
      ingredients: '#000000',
      instructionsTitle: ' #9C5988',
      instructions: '#000000',
    },
  },
  {
    number: 16,
    image: recipe16,
    title: 'Enjoy Dark Roast Bar',
    subtitle: 'In your Chocolate Shake !',
    ingredients: [
      '200ml Milk (chilled)',
      '40g Mother&apos;s Kitchen Dark Roast Bar (melted or finely chopped)',
      '30g Dry Fruits (almonds, cashews, walnuts – as per preference)',
      'Ice cubes (optional)',
      'Sugar or honey (optional, as per taste)',
    ],
    instructions: [
      '1. Melt the Dark Roast Bar – If using solid bar, melt it in a microwave or double boiler until smooth.',

      '2. Blend the Ingredients – In a blender, combine chilled milk, melted Dark Roast Bar, dry fruits, and ice cubes.',

      '3. ⁠Blend to Perfection – Process for 30-40 seconds until the mixture becomes smooth and creamy.',

      '4. ⁠Serve & Garnish – Pour into a glass and top with grated chocolate or finely chopped dry fruits.',

      'Enjoy your rich and indulgent Chocolate Dry Fruit Shake!',
    ],
    colors: {
      bg: '#F0DEB2',
      title: '#FFFFFF',
      subtitle: '#7D6F4E',
      ingredientsTitle: '#7D6F4E',
      ingredients: '#000000',
      instructionsTitle: '#7D6F4E',
      instructions: '#000000',
    },
  },
]
export default RecipesData
