import About from './About'
import Brands from './Brands'
import Comic from './Comic'
import Contact from './Contact'
import Home from './Home'
import MkCafe from './MkCafe'
import NotFound from './NotFound'
import Team from './Team'
import Recipes from './Recipes'
import Awards from './Awards'
import Pledge from './Pledge'
import Beauty from '../components/Beauty/beauty'
import Living from '../components/Living/living'
import Daksh from './Daksh'
export { Home, About, Team, Brands, Comic, MkCafe, Contact, NotFound, Recipes, Awards, Pledge, Beauty,Living,Daksh }
